image: node:10-alpine





cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/





stages:
  - test
  - pre-release
  - release





lint-and-spec:
  stage: test
  only:
    - master
    - /^(feature|release|v)\/.+$/
  coverage: '/^All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - npm install
    - npm run -s lint
    - npm test -- --ci --coverage
  artifacts:
    when: always
    expire_in: 3 mos
    reports:
      junit: junit.xml





raw-build:
  stage: test
  only:
    - master
    - /^(feature|release|v)\/.+$/
  script:
    - npm install
    - npm run build





shrinkwrap-build:
  stage: pre-release
  only:
    - /^(release|v)\/.+$/
  cache: {}
  script:
    - npm install
    - npm shrinkwrap
  artifacts:
    expire_in: 3 weeks
    paths:
      - npm-shrinkwrap.json





npm-publish:
  stage: release
  only:
    - /^v\/.+$/
  except:
    - branches
  dependencies:
    - shrinkwrap-build
  cache: {}
  script:
    - sh ./dev/publish.sh
  artifacts:
    paths:
      - npm-shrinkwrap.json
      - ngx-endpoint-*.tgz

