image: node:10-alpine


cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/


stages:
  - test
  - build
  - shrinkwrap
  - deploy






lint_and_spec:
  stage: test
  only:
    - master
    - /^feature\/.+$/
  script:
    - npm install
    - npm test -- --ci --coverage



raw_build:
  stage: build
  only:
    - master
    - /^feature\/.+$/
  script:
    - npm install
    - npm run build



shrinkwrap_build:
  stage: shrinkwrap
  only:
    - /^release\/.+$/
  except:
    - tags
  cache: {}
  script:
    - npm install
    - npm shrinkwrap
  artifacts:
    expire_in: 1 week
    paths:
      - npm-shrinkwrap.json



npm_publish:
  stage: deploy
  tags:
    - docker
  only:
    - /^v\/.+$/
  except:
      - branches
  script:
    - npm install
    - npm run build
    - cd dist/ngx-endpoint
    - cp ../../README.md .
    - cp ../../CHANGELOG.md .
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish $(npm pack -s)
  artifacts:
    paths:
      - "*.tgz"

