image: node:10-alpine




before_script:
  - export VERSION_CURRENT=$(npm run -s version)





cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/





stages:
  - test
  - scan
  - release





lint-and-spec:
  stage: test
  coverage: '/^All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - npm install
    - npm run -s lint
    - npm test -- --ci --coverage
  artifacts:
    when: always
    expire_in: 3 weeks
    paths:
      - coverage/lcov.info
    reports:
      junit: junit.xml





raw-build:
  stage: test
  script:
    - npm install
    - npm run build





sonar-scanner:
  image: node:10-slim
  stage: scan
  dependencies:
    - lint-and-spec
  script:
    - npx sonarqube-scanner
      -Dsonar.login=${SONARCLOUD_TOKEN}
      -Dsonar.projectVersion=${VERSION_CURRENT}
      -Dsonar.branch.name=${CI_COMMIT_REF_NAME}
  allow_failure: true





npm-publish:
  stage: release
  only:
    - /^v\/.+$/
  except:
    - branches
  cache: {}
  variables:
    NPM_DIST_TAG: next
  script:
    - sh ./dev/publish.sh
    - npm shrinkwrap
  artifacts:
    paths:
      - npm-shrinkwrap.json
      - ngx-endpoint-*.tgz





npm-tag-latest:
  stage: release
  only:
    - /^v\/.+$/
  except:
    - branches
  cache: {}
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm dist-tag add ngx-endpoint@${VERSION_CURRENT} latest
  when: manual

