image: node:10-alpine





cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/





stages:
  - test





lint_and_spec:
  stage: test
  tags:
    - gitlab-org
  only:
    - master
    - /^feature\/.+$/
  coverage: '/^All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - npm install
    - npm run -s lint
    - npm test -- --ci --coverage
  artifacts:
    expire_in: 1 week
    paths:
      - junit.xml
    reports:
      junit: junit.xml





raw_build:
  stage: test
  tags:
    - gitlab-org
  only:
    - master
    - /^feature\/.+$/
  script:
    - npm install
    - npm run build





shrinkwrap_build:
  tags:
    - gitlab-org
  only:
    - /^release\/.+$/
  except:
    - tags
  cache: {}
  script:
    - npm install
    - npm shrinkwrap
  artifacts:
    expire_in: 3 weeks
    paths:
      - npm-shrinkwrap.json





npm_publish:
  tags:
    - gitlab-org
  only:
    - /^v\/.+$/
  except:
    - branches
  cache: {}
  script:
    - npm install
    - npm run build
    - cd dist/ngx-endpoint
    - cp ../../LICENSE .
    - cp ../../README.md .
    - cp ../../CHANGELOG.md .
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish $(npm pack -s)
    - mv *.tgz ../../
  artifacts:
    paths:
      - '*.tgz'

