image: node:10-alpine





cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/





stages:
  - test
  - scan
  - pre-release
  - release





lint-and-spec:
  stage: test
  coverage: '/^All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - npm install
    - npm run -s lint
    - npm test -- --ci --coverage
  artifacts:
    when: always
    expire_in: 3 mos
    paths:
      - coverage/lcov.info
    reports:
      junit: junit.xml





raw-build:
  stage: test
  script:
    - npm install
    - npm run build





sonar-scanner:
  image: node:10-stretch
  stage: scan
  dependencies:
    - lint-and-spec
  script:
    - npx sonarqube-scanner
      -Dsonar.login=$SONARCLOUD_TOKEN
      -Dsonar.projectVersion=$(npm run -s version)
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
  allow_failure: true





shrinkwrap-build:
  stage: pre-release
  only:
    - /^(release|v)\/.+$/
  cache: {}
  script:
    - npm install
    - npm shrinkwrap
  artifacts:
    expire_in: 3 weeks
    paths:
      - npm-shrinkwrap.json





npm-publish:
  stage: release
  only:
    - /^v\/.+$/
  except:
    - branches
  dependencies:
    - shrinkwrap-build
  cache: {}
  variables:
    NPM_DIST_TAG: next
  script:
    - sh ./dev/publish.sh
  artifacts:
    paths:
      - npm-shrinkwrap.json
      - ngx-endpoint-*.tgz





npm-tag-latest:
  # only:
  #   - /^v\/.+$/
  # except:
  #   - branches
  when: manual
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm dist-tag add ngx-endpoint@$NPM_LATEST latest

